module.exports={
    addProductToCart:null,
    incrQuantity:null,
    decrQuantity:null,
    removeProduct:null,
    URL:'http://192.168.1.9/api/',
    onSignIn:null,
    goToSearch:null,
    setArraySearch:null
}